
stages:
  - test
  - build
  - deploy

build_app:
 stage: build
 image: docker:24.0.9
 services:
  - docker:24.0.9-dind
 variables:
  DOCKER_TLS_CERTDIR: "/certs"
 script:
  - docker build -t maniraja1122/mandoob .
  - docker login -u maniraja1122 -p $DOCK_PASS
  - docker push maniraja1122/mandoob

deploy:
  stage: deploy
  script: 
   - sleep 1
