
stages:
  - test
  - build
  - deploy

code_quality:
  stage: test
  image: "ghcr.io/cirruslabs/flutter:3.10.3"
  before_script:
    - flutter pub global activate dart_code_metrics
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

build_app:
 stage: build
 image: docker:24.0.9
 services:
  - docker:24.0.9-dind
 variables:
  DOCKER_TLS_CERTDIR: "/certs"
 script:
  - docker build -t maniraja1122/mandoob .
  - docker login -u maniraja1122 -p $DOCK_PASS
  - docker push maniraja1122/mandoob

deploy:
  stage: deploy
  script: 
   - sleep 1
